import type { Metadata } from 'next';
import { Schibsted_Grotesk, Martian_Mono } from 'next/font/google';
import './globals.css';
import LightRays from './lib/rays';
import Image from 'next/image';

const schibsted = Schibsted_Grotesk({
  variable: '--font-schibsted',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'], 
});

const martian = Martian_Mono({
  variable: '--font-martian',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'], 
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${schibsted.variable} ${martian.variable} min-h-screen antialiased`}>
        <div className="absolute inset-0 top-0 z-[-1] min-h-screen">
          <LightRays
            raysOrigin="top-center-offset"
            raysColor="#1814ff"
            raysSpeed={0.5}
            lightSpread={1.8}
            rayLength={2}
            followMouse={true}
            mouseInfluence={0.03}
            noiseAmount={0}
            distortion={0}
            className="custom-rays"
            pulsating={false}
            fadeDistance={1}
            saturation={1.2}
          />
        </div>
        <header>

        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
